####
# This Dockerfile is used in order to build a container that runs the Spring Boot application
#
###
FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/openjdk-21:1.18-4 as JAR_EXTRACT
USER root
WORKDIR /app
ARG JAR_FILE=*.jar
COPY target/${JAR_FILE} ./app.jar
RUN java -Djarmode=layertools -jar ./app.jar extract

####
FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/openjdk-21:1.18-3
ARG APP_NAME=todo-application
ARG APP_VERSION=0.0.1-SNAPSHOT
ARG GIT_COMMIT_SHA=
ARG GIT_COMMIT_BRANCH=develop

# Labels
LABEL maintainer="Red Hat Open Innovation Labs <open-innovation-labs@redhat.com>"
LABEL app-name="$APP_NAME"
LABEL app-version="$APP_VERSION"
LABEL git-commit-sha="$GIT_COMMIT_SHA"
LABEL git-commit-branch="$GIT_COMMIT_BRANCH"

USER root

# Working directory
WORKDIR /application

# Copy all dependencies
COPY --from=JAR_EXTRACT /app/dependencies ./
COPY --from=JAR_EXTRACT /app/spring-boot-loader ./
COPY --from=JAR_EXTRACT /app/snapshot-dependencies ./
COPY --from=JAR_EXTRACT /app/application ./

# Exposing port 8080
EXPOSE 8080

# Entrypoint
ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-Djava.security.egd=file:/dev/./urandom", "org.springframework.boot.loader.launch.JarLauncher"]