apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: todo-app
  labels:
    app: postgresql
    service: postgresql
spec:
  ports:
  - port: 5432
    name: tcp
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: todo-app
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: registry.access.redhat.com/rhel8/postgresql-16:1-21
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRESQL_ADMIN_PASSWORD
          value: "P4ssw0rd123"
        - name: POSTGRESQL_USER
          value: "todo-user"
        - name: POSTGRESQL_PASSWORD
          value: "password"
        - name: POSTGRESQL_DATABASE
          value: "todo"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        - name: POSTGRESQL_MAX_CONNECTIONS
          value: "50"
        ports:
        - containerPort: 5432
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: [ "ALL" ]
          seccompProfile:
            type: RuntimeDefault