server:
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASSNAME:org.h2.Driver}
    url: ${DATASOURCE_URL:jdbc:h2:mem:todo}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:password}

  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # setup local h2 database console
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
      settings:
        web-allow-others: false

  thymeleaf:
    cache: false

app:
  kafka:
    todo:
      topic-name: ${APP_TODO_TOPIC:todo-dev}

logging:
  level:
    root: INFO
    com.example.todo: DEBUG