# setup database config
spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASSNAME:org.postgresql.Driver}
    url: ${DATASOURCE_URL:jdbc:postgresql://todo-java-db-svc:5432/todo-java-sit-db}
    username: ${DATASOURCE_USERNAME:}
    password: ${DATASOURCE_PASSWORD:}
  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # setup local h2 database console
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      path: /h2-console
      settings:
        web-allow-others: false

  # additional config for producer/consumer
  kafka:
    security:
      protocol: "PLAINTEXT"
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: group1
  #    ssl:
  #      trust-store-location: classpath:/certs/kafka.client.truststore.jks
  #      trust-store-password: password
  #      key-store-location:  classpath:/client-certs/kafka.client.keystore.jks
  #      key-store-password: <password>

  thymeleaf:
    cache: false

app:
  kafka:
    todo:
      topic-name: ${APP_TODO_TOPIC:todo-sit}

  logging:
    level:
      root: INFO
      com.example.todo: INFO